# Generated by Django 5.2.17 on 2026-09-15 23:48

import athena.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='título')),
                ('slug', models.SlugField(help_text='Se conserva después de crear el artículo para mantener sus enlaces.', max_length=180, unique=True, verbose_name='dirección')),
                ('kind', models.CharField(choices=[('guide', 'Guía'), ('page', 'Página'), ('tool', 'Herramienta'), ('announcement', 'Anuncio'), ('release', 'Versión')], default='guide', max_length=20, verbose_name='tipo')),
                ('summary', models.CharField(max_length=1000, verbose_name='resumen')),
                ('author', models.CharField(max_length=240, verbose_name='autor')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiquetas')),
                ('body', models.TextField(blank=True, verbose_name='contenido Markdown')),
                ('status', models.CharField(blank=True, choices=[('stable', 'Estable'), ('alpha', 'Alfa'), ('coming-soon', 'Próximamente')], max_length=20, verbose_name='estado de herramienta')),
                ('url', models.URLField(blank=True, verbose_name='sitio oficial')),
                ('download_file', models.CharField(blank=True, max_length=240, verbose_name='descarga aprobada')),
                ('published', models.BooleanField(default=False, verbose_name='publicado')),
                ('pdf', models.BinaryField(blank=True, default=bytes)),
                ('pdf_name', models.CharField(blank=True, editable=False, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('scope', models.CharField(choices=[('read', 'Lectura'), ('articles', 'Administrar artículos'), ('admin', 'Administrar usuarios y artículos')], default='read', max_length=10, verbose_name='permiso')),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('password_digest', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField(default=athena.models.token_expiry, verbose_name='vence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'clave de API',
                'verbose_name_plural': 'claves de API',
            },
        ),
    ]
