# Generated by Django 5.2.17 on 2026-09-24 00:57

import athena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='título')),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True, verbose_name='dirección')),
                ('section', models.CharField(choices=[('framework', 'Framework'), ('packages', 'Paquetes'), ('exercises', 'Ejercicios'), ('previous', 'Versiones anteriores')], default='framework', max_length=20, verbose_name='sección')),
                ('file', models.FileField(max_length=300, storage=athena.models.KeepNameStorage(), upload_to='downloads/', verbose_name='archivo')),
                ('size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='tamaño')),
                ('sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='nota')),
                ('published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'descarga',
                'verbose_name_plural': 'descargas',
                'ordering': ['section', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='lockouts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
