# Generated by Django 5.2.17 on 2026-09-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0002_downloads_and_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_only',
            field=models.BooleanField(default=False, help_text='El PDF adjunto es el contenido del artículo. El lector no ofrece «Exportar PDF».', verbose_name='solo PDF'),
        ),
    ]
