# Generated by Django 5.2.17 on 2026-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0003_article_pdf_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si está publicado, cualquier persona puede leer el artículo y sus PDF sin una cuenta. Los borradores siguen restringidos.', verbose_name='acceso público'),
        ),
    ]
