# Generated by Django 5.2.17 on 2026-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0005_managedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedimage',
            name='format',
            field=models.CharField(choices=[('png', 'PNG'), ('jpg', 'JPEG'), ('webp', 'WebP'), ('gif', 'GIF')], max_length=4),
        ),
    ]
